### ISSUE TITLE
2019年机试第五题捉个虫

### ISSUE THREAD

**Issue by anyin233** [zdszero/ustc-cs-graduate#2]
你好，关于您文章中2019年机试题第五题我认为解法可能有问题，实际上本题可能存在一个不会经过根结点的最短路径。本题实际上可以转换为求一颗树的直径的模板问题，我的解法在[这里](https://anyin233.github.io/2022/03/02/%E4%B8%AD%E7%A7%91%E5%A4%A72019-5/)

**Comment by zdszero** [comment]
已经修改了原来的解答，将答案引到了你的博文，谢谢你的提醒！
